// auth
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED"
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET"

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED"
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET"

export const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST"
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS"
export const USER_SIGNOUT_FAILED = "USER_SIGNOUT_FAILED"
export const USER_SIGNOUT_RESET = "USER_SIGNOUT_RESET"
