// auth
const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED"
const USER_SIGNIN_RESET = "USER_SIGNIN_RESET"

const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST"
const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS"
const USER_SIGNOUT_FAILED = "USER_SIGNOUT_FAILED"
const USER_SIGNOUT_RESET = "USER_SIGNOUT_RESET"
